### ISSUE TITLE
Compiling from source

### ISSUE THREAD

**Issue by orliac** [ratt-ru/casa-arrow#11]
Hi.
I'm trying to compile casa-arrow from source with Spack (with GCC 9.3.0 and Python 3.10 on a RH7 system).
Regarding the "custom Python 3.8 pyarrow manylinux_2_28 wheel" listed in the requirements, is the source code publicly available? When trying to install from the wheel I get compatibility issue (`ERROR: pyarrow-12.0.0.dev13242+gdbb4473-cp38-cp38-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.`) so I would like to install it from source.
Thank you.

**Comment by sjperkins** [comment]
Hi @orliac. Yes the source code is available at https://github.com/apache/arrow

The manylinux-2-28 pyarrow wheel is useful for development environments where the newer C++11 ABI is configured:  `-D_GLIBCXX_USE_CXX11_ABI=1`. 

If you can use the older ABI `-D_GLIBCXX_USE_CXX11_ABI=0`, it should be  possible to use the `manylinux2014` pyarrow 12.0.0 wheels. https://github.com/ratt-ru/casa-arrow/blob/master/docker/py310-wheel-manylinux2014.docker should provide insight on how to build this from scratch.

Also pyarrow 13.0.0 should provide manylinux-2-28 wheels https://github.com/apache/arrow/issues/33804

**Comment by orliac** [comment]
Hi @sjperkins,
Many thanks for the feedback. I thought the wheel was built from a fork with some in house implementations, hence my request.
Closing the Issue since I could install from source and run the provided example with minor changes with Python 3.10.
