### ISSUE TITLE
Re-enable python-casacore install for 3.11

### ISSUE THREAD

**Issue by sjperkins** [ratt-ru/casa-arrow#26]
We currently don't install python-casacore for 3.11 as no wheel is available

- https://github.com/casacore/python-casacore/issues/244

**Comment by tammojan** [comment]
Added it to pypi just now, sorry for the delay.

**Comment by sjperkins** [comment]
> Added it to pypi just now, sorry for the delay.

Thanks @tammojan, that was really quick. I feel bad -- I should've tagged this with low priority because we only use python-casacore for testing, so missing the matrix on 3.11 wasn't a critical gap!

**Comment by tammojan** [comment]
Luckily there are also other users! You were the third user asking, so I thought this would be a good time :)
